---
version: '2.2'
services:
  fah:
    build: build
    image: neofob/fah:${TAG:-latest}
    volumes:
      - fahclient:/var/lib/fahclient
    network_mode: bridge
    container_name: FAH
    hostname: fah
    restart: always
    ports:
      - 7396:7396
    cpus: 4
    mem_limit: 1G
    environment:
      FAH_USER: neofob
      FAH_PASSKEY: ""
      FAH_TEAM: "0"
      FAH_CLIENT_TYPE: "beta"
      # Use some fancy script
      # FAH_HOST_IP=`get_host_ip.sh` docker-compose up -d
      FAH_HOST_IP: ${FAH_HOST_IP}
    logging:
      options:
        max-size: "640k"
        max-file: "1"

volumes:
  fahclient:
