version: '3'
services:
  fah:
    build: ./build/Dockerfile
    image: neofob/fah:${TAG:-latest}
    ports:
      - 7396:7396
    volumes:
      - ${CONFIG_FILE:-./build/config.xml}:/etc/fahclient/config.xml
      - fahclient:/var/lib/fahclient
    network_mode: bridge
    container_name: FAH
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      options:
        max-size: "640k"
        max-file: "1"

volumes:
  fahclient:
